name: Bug report
description: File a bug report
labels: ["type: bug", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Search tip: `label:"type: bug"`
      options:
        - label: I have searched the existing issues.
          required: true

  - type: text
    id: version
    attributes:
      label: Version
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: Describe the bug and the steps to reproduce it.
      placeholder: |
        What happened?
        What should have happened?
        ...
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output
      description: If applicable, paste output here.
      render: shell
